export const StaticData = {
Meta_title:" pacific smiles dental",
Meta_description:"pacific smiles dental provide a unique approach to ",
locator_breadcrumb:"Dental Locator",
facilities:"Facilities:",
Telephone:"Telephone",
openingHours:"Opening Hours",
FindLocationtext:"Find a centre",
Usemylocation:"Use my location",
chargerId:"Charger ID",
Status:"Status",
bannerCta:"Book your dental appointment",
Availability:"Chargers Available",
Unavailable:"No Chargers available",
Search:"Search",
Brandname:"pacific smiles dental",
miles:"miles",
tempClosed:"Temporarily Closed",
StoreDetailbtn:"View Store",
bookNow:"Book Now",
noStationFound:"Please enter your suburb to find your nearest dental centre.",
Storehighlight:"Store Highlights",
Days:"Days",
Hours:"Hours",
Minutes:"Minutes",
Seconds:"Seconds",
getDirection:"Directions",
AllCity:"All State of",
NearStoretext:"NEARBY LOCATIONS",
AllLocationtext:"View All Location",
PagenotFound:"404 - Page Not Found",
goHomeCTA:"GO HOME",
StoreFinder:"Store Finder",
FAQs:"FAQs",
DownloadApp:"Download Our App",
cookie:"Privacy & Cookies Policy I pacific smiles dental",
About:"pacific smiles dental We care about your Teeth.",
aboutKerb:"ABOUT pacific smiles dental",
Closed:"Closed",
DayofWeek:"Day of the Week",
Reopenmessage:"Message - The Station is temporarily closed. It will reopen at",
Address:"Address",
Holdiay:"Our Holdiday Hours",
BacktoTop:"Back to Top",
bannerHeading:"Australia's Local Dentist",
bannerPara:"As Australia’s local Dentist with over 110 locations and counting, no matter where you’re smiling – we’re there. Or will be soon",
}